{% set name = "postgis" %}
{% set version = "3.0.0alpha3" %}
{% set sha256 = "b75e28139fe74158a27b7e7b2d1c2c0a7acb3abe8c60cfc72d45b0827dd12364" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://download.osgeo.org/{{ name }}/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # - 0001-gdal-test.patch

build:
  number: 0
  skip: True  # [ win ]

requirements:
  build:
    - {{ compiler('c') }}
    - libxslt
  host:
    - cunit
    - gdal >=1.8
    - geos >=3.6
    - gettext
    - pcre
    - proj4 >=4.6.0
    - json-c >=0.9
    - perl
    - postgresql >=9.5
    - libXML2 >=2.5

  run:
    - gdal >=1.8
    - gettext
    - pcre
    - proj4 >=4.6.0
    - json-c >=0.9
    - postgresql >=9.5
    - geos >=3.6
    - libXML2 >=2.5


test:
  commands:
    - shp2pgsql
    - pgsql2shp
    - raster2pgsql

about:
  home: http://postgis.net
  license: GPL2
  license_family: GPL
  license_file: LICENSE.TXT
  summary: 'PostGIS adds geometry, geography, raster and other types to the PostgreSQL database.'

  description: |
    PostGIS is a spatial database extender for PostgreSQL object-relational
    database. It adds support for geographic objects allowing location
    queries to be run in SQL.
  doc_url: http://postgis.net/docs/manual-2.3/
  dev_url: http://svn.osgeo.org/postgis/

extra:
  recipe-maintainers:
    - sodre
    - dwnoble
